#this file represents the controller being used
march:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  # pid stands for proportional integral derivative controller
  left_hip_position_controller:
    type: position_controllers/JointPositionController
    joint: left_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_knee_position_controller:
    type: position_controllers/JointPositionController
    joint: left_knee
    pid: {p: 100.0, i: 0.01, d: 10.0}

  left_ankle_position_controller:
    type: position_controllers/JointPositionController
    joint: left_ankle
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_hip_position_controller:
    type: position_controllers/JointPositionController
    joint: right_hip
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_knee_position_controller:
    type: position_controllers/JointPositionController
    joint: right_knee
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_ankle_position_controller:
    type: position_controllers/JointPositionController
    joint: right_ankle
    pid: {p: 100.0, i: 0.01, d: 10.0}